# Ansible managed

[DEFAULT]
debug = True
enabled_network_interfaces = noop
default_network_interface = noop
default_deploy_interface = direct
enabled_inspect_interfaces = no-inspect,agent
default_inspect_interface = agent
enabled_bios_interfaces = no-bios,redfish
enabled_boot_interfaces = ipxe,pxe,redfish-virtual-media
enabled_firmware_interfaces = no-firmware,redfish
enabled_management_interfaces = noop,ipmitool,redfish
enabled_power_interfaces = fake,ipmitool,redfish
enabled_deploy_interfaces = direct,ramdisk
enabled_raid_interfaces = no-raid,agent,redfish
enabled_vendor_interfaces = no-vendor,ipmitool,redfish

enabled_hardware_types = ipmi,redfish,manual-management


default_resource_class = baremetal

rpc_transport = none

auth_strategy = noauth
http_basic_auth_user_file = /etc/ironic/htpasswd


isolinux_bin = /usr/lib/ISOLINUX/isolinux.bin

grub_config_path = EFI/ubuntu/grub.cfg


[agent]
deploy_logs_collect = always
deploy_logs_local_path = /var/log/ironic/deploy

[pxe]
#kernel_append_params = nofb nomodeset systemd.journald.forward_to_console=yes  ipa-insecure=1
kernel_append_params = systemd.journald.forward_to_console=yes ipa-insecure=1 earlycon=efifb earlyprintk=efi,keep mem=8G ipa-inspection-dhcp-all-interfaces=0 ipa-interfaces=BOOTIF systemd.mask=systemd-networkd-wait-online.service systemd.mask=NetworkManager-wait-online.service
#kernel_append_params = nofb nomodeset systemd.journald.forward_to_console=yes ipa-insecure=1 mem=8G rd.net.timeout.carrier=2 rd.net.timeout.dhcp=2
tftp_server = 192.168.240.1
tftp_root = /var/lib/tftpboot
ipxe_fallback_script = pxelinux.cfg/default
tftp_master_path = /var/lib/ironic/master_images
uefi_ipxe_bootfile_name = snponly.efi
enable_netboot_fallback = true

[deploy]
http_url = http://192.168.240.1:8080/
http_root = /var/lib/ironic/httpboot
default_boot_option = local
default_boot_mode = uefi
fast_track = True
erase_devices_priority = 0
erase_devices_metadata_priority = 10

[conductor]
automated_clean = true
deploy_kernel = http://192.168.240.1:8080/ipa.kernel
deploy_ramdisk = http://192.168.240.1:8080/ipa.initramfs
rescue_kernel = http://192.168.240.1:8080/ipa.kernel
rescue_ramdisk = http://192.168.240.1:8080/ipa.initramfs
bootloader = http://192.168.240.1:8080/esp.img

[database]
connection = mysql+pymysql://ironic:D7i0GPzEk2r3Ce1YqbND@localhost/ironic?charset=utf8

[dhcp]
dhcp_provider = dnsmasq

[dnsmasq]
dhcp_hostsdir = /etc/dnsmasq.d/bifrost.dhcp-hosts.d
dhcp_optsdir = /etc/dnsmasq.d/bifrost.dhcp-opts.d
dhcp_leasefile = /var/lib/misc/dnsmasq.leases


[ipmi]
debug = False
disable_boot_timeout = True

[redfish]
verify_ca = False
use_swift = False
#kernel_append_params = nofb nomodeset systemd.journald.forward_to_console=yes  ipa-insecure=1  
kernel_append_params = nofb nomodeset systemd.journald.forward_to_console=yes ipa-insecure=1 ignore_loglevel initcall_debug earlyprintk=efi,keep mem=8G ipa-disable-glean=1
#kernel_append_params = nofb nomodeset systemd.journald.forward_to_console=yes ipa-insecure=1 mem=8G ipa-disable-glean=1

[inspector]
power_off = False
#extra_kernel_params = ipa-inspection-collectors=default,logs
extra_kernel_params = ipa-inspection-collectors=default,logs mem=8G ignore_loglevel initcall_debug earlyprintk=efi,keep
hooks = $default_hooks
require_managed_boot = False
force_dhcp = False
add_ports = pxe
keep_ports = present

[auto_discovery]
enabled = False
driver = ipmi


[service_catalog]
auth_type = http_basic
username = admin
password = yRoxd5-L0zNbz6E2lD8R
# NOTE(dtantsur): this has to be on internal IP even if public IPs are used
endpoint_override = http://192.168.240.1:6385




[oci]
permit_fallback_to_http_transport = True

